- block:
  - name: Create vdsm and QEMU key temporary files
    tempfile:
      state: file
      suffix: '{{ item.suffix }}'
    with_items:
      - suffix: vdsm
        pending_file: '{{ ovirt_vdsm_key_pending_file }}'
        req_dir: requests
      - suffix: qemu
        pending_file: '{{ ovirt_qemu_key_pending_file }}'
        req_dir: requests-qemu
    register: vdsmkeys

  - name: Generate vdsm and QEMU CSRs
    command: |
      '/usr/bin/openssl'
      'req'
      '-new'
      '-newkey'
      '{{ ovirt_vdsm_key_type }}:{{ ovirt_vdsm_key_size }}'
      '-nodes'
      '-subj'
      '/'
      '-keyout'
      '{{ item.path }}'
    loop: '{{ vdsmkeys.results }}'
    register: csrs

  - block:
    - name: Create vdsm and QEMU key directories
      file:
        dest: "{{ vdsm_truststore ~ '/' ~ item.item.pending_file | dirname }}"
        state: directory
        owner: 'vdsm'
        group: 'kvm'
        mode: 0700
      loop: '{{ vdsmkeys.results }}'

    - name: Create vdsm and QEMU key pending files
      copy:
        src: "{{ item.path }}"
        dest: "{{ vdsm_truststore }}/{{ item.item.pending_file }}"
        owner: root
        mode: 0400
        remote_src: yes
      loop: '{{ vdsmkeys.results }}'
    when: "ovirt_enrollment_type == certificate_enrollment_request"

  - block:
    - name: Copy vdsm and QEMU CSRs
      copy:
        content: "{{ item.stdout }}"
        dest: "{{ ovirt_pki_dir }}/{{ item.item.item.req_dir }}/{{ ovirt_vds_hostname }}.req"
      loop: '{{ csrs.results }}'
      delegate_to: localhost

    - name: Run PKI enroll request for vdsm and QEMU
      command: |
         "{{ ovirt_engine_usr }}/bin/pki-enroll-request.sh"
         "--name={{ ovirt_vds_hostname }}"
         "--subject=/O={{ ovirt_organizationname }}/CN={{ ovirt_vds_hostname }}{{ item.ou }}"
         "--san={{ ovirt_san }}"
         "--days={{ ovirt_vdscertificatevalidityinyears | int * 365 }}"
         "--timeout={{ ovirt_signcerttimeoutinseconds }}"
         "--ca-file={{ item.ca_file }}"
         "--cert-dir={{ item.cert_dir }}"
         "--req-dir={{ item.req_dir }}"
      with_items:
        - ou: ''
          ca_file: 'ca'
          cert_dir: 'certs'
          req_dir: 'requests'
        - ou: '/OU=qemu'
          ca_file: 'qemu-ca'
          cert_dir: 'certs-qemu'
          req_dir: 'requests-qemu'
      register: certrequest
      delegate_to: localhost


    - name: Prepare directories for vdsm certificate files
      file:
        dest: "{{ filedest }}"
        state: directory
        owner: 'vdsm'
        group: 'kvm'
      with_items:
        - "{{ ovirt_vdsm_trust_store ~ '/' ~ ovirt_vdsm_ca_file | dirname }}"
        - "{{ ovirt_vdsm_trust_store ~ '/' ~ ovirt_vdsm_key_file | dirname }}"
        - "{{ ovirt_vdsm_trust_store ~ '/' ~ ovirt_qemu_ca_file | dirname }}"
        - "{{ ovirt_vdsm_trust_store ~ '/' ~ ovirt_qemu_key_file | dirname }}"
        - "{{ ovirt_vdsm_trust_store ~ '/' ~ ovirt_vdsm_spice_cert_file | dirname }}"
        - "{{ ovirt_libvirt_default_trust_store ~ '/' ~ ovirt_libvirt_default_client_key_file | dirname }}"
        - "{{ ovirt_libvirt_default_trust_store ~ '/' ~ ovirt_libvirt_default_client_ca_file | dirname }}"
      loop_control:
        loop_var: filedest

    - name: Add vdsm cacert files
      copy:
        content: "{{ ovirt_ca_cert }}"
        dest: "{{ filedest }}"
        owner: 'root'
        group: 'kvm'
        mode: 0644
      with_items:
        - "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_ca_file }}"
        - "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_spice_ca_file }}"
        - "{{ ovirt_libvirt_default_trust_store }}/{{ ovirt_libvirt_default_client_ca_file }}"
      loop_control:
        loop_var: filedest

    - name: Add QEMU cacert file
      copy:
        content: "{{ ovirt_qemu_ca_cert }}"
        dest: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_qemu_ca_file }}"
        owner: 'root'

    - name: Add vdsm cert files
      copy:
        src: "{{ ovirt_pki_dir }}/certs/{{ ovirt_vds_hostname }}.cer"
        dest: "{{ filedest }}"
        owner: 'root'
        group: 'kvm'
        mode: 0644
        remote_src: no
      with_items:
        - "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_cert_file }}"
        - "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_spice_cert_file }}"
        - "{{ ovirt_libvirt_default_trust_store }}/{{ ovirt_libvirt_default_client_cert_file }}"
      loop_control:
        loop_var: filedest

    - name: Add QEMU cert file
      copy:
        src: "{{ ovirt_pki_dir }}/certs-qemu/{{ ovirt_vds_hostname }}.cer"
        dest: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_qemu_cert_file }}"
        owner: 'root'
        remote_src: no

    - name: Set vdsm key path
      set_fact:
        vdsmkey_path: "{{ ovirt_vdsm_trust_store~'/'~ovirt_vdsm_key_pending_file
            if ovirt_enrollment_type == certificate_enrollment_accept
            else vdsmkeys.results[0].path  }}"

    - name: Add vdsm key files
      copy:
        src: "{{ vdsmkey_path }}"
        dest: "{{ filedest }}"
        owner: 'vdsm'
        group: 'kvm'
        mode: 0440
        remote_src: yes
      with_items:
        - "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_key_file }}"
        - "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_spice_key_file }}"
        - "{{ ovirt_libvirt_default_trust_store }}/{{ ovirt_libvirt_default_client_key_file }}"
      loop_control:
        loop_var: filedest

    - name: Set QEMU key path
      set_fact:
        qemukey_path: "{{ ovirt_vdsm_trust_store~'/'~ovirt_qemu_key_pending_file
            if ovirt_enrollment_type == certificate_enrollment_accept
            else vdsmkeys.results[1].path  }}"

    - name: Add QEMU key file
      copy:
        src: "{{ qemukey_path }}"
        dest: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_qemu_key_file }}"
        owner: 'root'
        group: 'qemu'
        mode: 0440
        remote_src: yes
    when: "ovirt_enrollment_type != certificate_enrollment_request"

  always:
    - name: Remove temp file
      file:
        state: absent
        path: "{{ item.path }}"
      loop: "{{ vdsmkeys.results }}"
