---
- name: Examine target directory
  ansible.builtin.stat:
    path: "{{ target_directory }}"
  register: target_directory_stats

- name: Fail if target directory does not exist
  ansible.builtin.fail:
    msg: "Target directory does not exist"
  when: not target_directory_stats.stat.exists

- name: Fail if target directory is not a directory
  ansible.builtin.fail:
    msg: "Target directory is not a directory"
  when: not target_directory_stats.stat.isdir

- name: Fail if target directory is not writeable
  ansible.builtin.fail:
    msg: "Target directory is not writeable"
  when: not target_directory_stats.stat.writeable

- name: Removing the temporary file
  ansible.builtin.file:
    path: "{{ target_directory }}/{{ ova_name }}.tmp"
    state: absent
  when: validate_only is not defined

- name: Allocating the temporary path for the OVA file
  ansible.builtin.command: xfs_mkfile -n "{{ ova_size }}" "{{ target_directory }}/{{ ova_name }}.tmp"
  async: "{{ ansible_timeout }}"
  poll: 15
  when: validate_only is not defined

- name: Retrieving the temporary path for the OVA file
  ansible.builtin.file:
    path: "{{ target_directory }}/{{ ova_name }}.tmp"
    state: touch
  register: ova_file
  when: validate_only is not defined
