---
- name: Verify hosted engine conf file exists
  stat:
    path: "{{ hosted_engine_conf }}"
  register: stat_results

- name: Remove hosted engine configuration
  copy:
    dest: hosted_engine_conf
    content: ''
  when: stat_results.stat.exists == true

- name: Remove hosted engine conf file
  file:
    path: "{{ hosted_engine_conf }}"
    state: absent

- name: Stop ovirt-ha-agent service
  service:
    name: ovirt-ha-agent
    state: stopped