---
- name: Create SPICE config file with the right permissions
  ansible.builtin.file:
    dest: '/etc/pki/tls/spice.cnf'
    state: touch
    mode: 0644
    owner: root
    group: root

- name: Put cipher string to SPICE config file
  ansible.builtin.copy:
    dest: '/etc/pki/tls/spice.cnf'
    backup: true
    mode: 0644
    content: |
      CipherString = {{ host_deploy_spice_cipher_string }}
      Protocol = {{ host_deploy_spice_protocol }}
