---
- block:
  - name: Install ovs
    yum:
        name: openvswitch
        state: present

  - name: Ensure Open vSwitch is started
    service:
        name: openvswitch
        state: started
        enabled: yes

  when:
    - cluster_switch == "ovs" or (ovn_central is defined and ovn_central | ipaddr and ovn_engine_cluster_version is version_compare('4.2', '>='))

- block:
  - name: Install ovirt-provider-ovn-driver
    package:
        name: ovirt-provider-ovn-driver
        state: present

  - name: Ensure ovn-controller is started
    service:
        name: ovn-controller
        state: started
        enabled: yes

  - name: Configure OVN for oVirt
    command: >
        vdsm-tool ovn-config {{ ovn_central }} {{ ovn_tunneling_interface }}

  when:
    - ovn_engine_cluster_version is version_compare('4.2', '>=')
    - ovn_central is defined
    - ovn_central | ipaddr
