---
- name: Create SASL QEMU config file
  ansible.builtin.blockinfile:
    path: '/etc/sasl2/qemu.conf'
    state: present
    create: true
    block: |
      mech_list: scram-sha-256
      sasldb_path: /etc/sasl2/vnc_passwd.db

- name: Use saslpasswd2 to create file with dummy user
  ansible.builtin.command: saslpasswd2 -a dummy_db -f /etc/sasl2/vnc_passwd.db dummy_user -p
  args:
    stdin: dummy_password
    creates: '/etc/sasl2/vnc_passwd.db'

- name: Set ownership of the password db
  ansible.builtin.file:
    group: 'qemu'
    owner: 'qemu'
    state: 'file'
    path: '/etc/sasl2/vnc_passwd.db'

- name: Modify qemu config file - enable VNC SASL authentication
  ansible.builtin.lineinfile:
    path: '/etc/libvirt/qemu.conf'
    state: present
    line: 'vnc_sasl=1'
  notify:
    populate service facts and restart libvirtd
