---
# Fluentd service name.
fluentd_service_name: fluentd

# Path to the Fluentd configuration directory.
fluentd_config_dir: /etc/fluentd

# Path to the main Fluentd configuration file.
fluentd_config_file: '{{ fluentd_config_dir }}/fluent.conf'

# Path to the directory containing Fluentd configuration snippets.
fluentd_config_parts_dir: '{{ fluentd_config_dir }}/config.d'

# User that will own Fluentd config files.
fluentd_owner: root

# Group that will own Fluentd config files.
fluentd_group: fluentd

# File mode for Fluentd configuration files.
fluentd_config_mode: 0640

# File mode for Fluentd configuration directories.
fluentd_config_dir_mode: 0750

# Set to true if Fluentd should use SSL.
fluentd_use_ssl: false

# Shared secret key for SSL connections.
fluentd_shared_key:

# Where to find the Fluentd server certificate authority certificate.
fluentd_ca_cert_path: '{{ fluentd_config_dir }}/ca_cert.pem'

# Content of an x509 certificate that will be used to identify the
# server to clients.
fluentd_ca_cert:
