---
- name: Run packing script
  script: >
    pack_ova.py
    "{{ entity_type }}"
    "{{ ova_file.dest }}"
    "{{ ovirt_ova_pack_ovf }}"
    "{{ ovirt_ova_pack_disks }}"
    "{{ ovirt_ova_pack_tpm }}"
    "{{ ovirt_ova_pack_nvram }}"
    "{{ ovirt_ova_pack_padding }}"
  args:
    executable: "{{ ansible_python_interpreter }}"
  register: packing_result
  ignore_errors: yes
  when: ova_file is defined and ova_file.dest is defined
