dependencies:
  - ovirt-host-deploy-facts
  - ovirt-host-deploy-vdsm
  - ovirt-host-deploy-misc
  - ovirt-host-deploy-ovn-certificates
  - ovirt-provider-ovn-driver
  - ovirt-host-deploy-libvirt-guests
  - ovirt-host-deploy-firewalld
  - ovirt-host-deploy-vnc-certificates
  - ovirt-host-deploy-kernel
  - ovirt-host-deploy-vm-console
  - ovirt-host-deploy-iptables
  - ovirt-host-deploy-hosted-engine
